package com.banking.common.exception;

public enum ErrorCode {

    GATEWAY_UNAUTHORIZED,
    GATEWAY_TOKEN_EXPIRED,
    GATEWAY_FORBIDDEN,
    GATEWAY_INVALID_HEADER,
    GATEWAY_RATE_LIMIT_EXCEEDED,
    GATEWAY_CIRCUIT_BREAKER_OPEN,

    AUTH_INVALID_CREDENTIALS,
    AUTH_USER_NOT_FOUND,
    AUTH_TOKEN_REVOKED,
    AUTH_TOKEN_INVALID,
    AUTH_ACCOUNT_LOCKED,
    AUTH_TOO_MANY_ATTEMPTS,

    ACCOUNT_NOT_FOUND,
    ACCOUNT_LOCKED,
    ACCOUNT_BALANCE_INSUFFICIENT,
    ACCOUNT_TYPE_INVALID,
    ACCOUNT_ALREADY_EXISTS,

    // === Transaction Service ===
    TX_LIMIT_EXCEEDED,
    DUPLICATE_TX_REQUEST,
    TX_INVALID_REFERENCE,
    TX_CURRENCY_MISMATCH,
    TX_FRAUD_SUSPECTED,
    TX_REQUIRES_2FA,

    // === FX Service ===
    FX_RATE_NOT_FOUND,
    FX_PAIR_UNSUPPORTED,
    FX_AMOUNT_TOO_LOW,

    NOTIFY_CHANNEL_UNSUPPORTED,
    NOTIFY_DELIVERY_FAILED,

    AUDIT_EVENT_FAILED,

    BAD_REQUEST,
    VALIDATION_ERROR,
    MISSING_REQUIRED_FIELD,
    UNSUPPORTED_MEDIA_TYPE,
    INVALID_DATE_FORMAT,

    INTERNAL_ERROR,
    SERVICE_UNAVAILABLE,
    DEPENDENCY_FAILURE,
    TIMEOUT_OCCURRED,

    BUSINESS_RULE_VIOLATION,
    OPERATION_NOT_ALLOWED,
    DUPLICATE_REQUEST;

    public String code() {
        return this.name();
    }
}
